version: "3.9"

volumes:
  repository:
  auth:
  fuseki-default:

services:
  web:
    image: ${IMAGE_NAMESPACE}/cometar/cometar-web
    # build:
    #   context: ./web
    #   dockerfile: Dockerfile
    ports:
      - 80:80
    container_name:
      cometar_web
    env_file:
      - .env
    volumes:
      - auth:/etc/nginx/auth
    depends_on:
      - "rest"
      - "git"
  git:
    image: ${IMAGE_NAMESPACE}/cometar/cometar-git
    # build:
    #   context: ./git
    #   dockerfile: Dockerfile
    container_name:
      cometar_git
    env_file:
      - .env
    volumes:
      - repository:/git
      - auth:/etc/nginx/auth
    depends_on:
      - "rest"
  rest:
    image: ${IMAGE_NAMESPACE}/cometar/cometar-rest
    # build:
    #   context: ./rest
    #   dockerfile: Dockerfile
    container_name:
      cometar_rest
    volumes:
      - repository:/update-hook-repository:ro
    depends_on:
      - "fuseki"
  fuseki:
    image: ${IMAGE_NAMESPACE}/cometar/cometar-fuseki
    # build:
    #   context: ./fuseki
    #   dockerfile: Dockerfile
    container_name:
      cometar_fuseki
    volumes:
      - fuseki-default:/fuseki
