version: "3.9"

volumes:
  repository:
  auth:
  fuseki-default:

services:
  git-web:
    build:
      context: ./browser
      dockerfile: Dockerfile
    ports:
      - 80:80
    container_name:
      cometar_git-web
    environment:
      - BROWSER_FQDN=localhost
      - BROWSER_PORT=80
      - BROWSER_SCHEME=http
      ## Trusted IP ranges, eg internal/VPN networks. Comma separated CIDR blocks or ip addresses
      ## https://nginx.org/en/docs/http/ngx_http_access_module.html
      - FUSEKI_ADMIN_ALLOW_RANGE=127.0.0.0/8,192.168.0.0/16,10.0.0.0/8
      - REST_ALLOW_RANGE=127.0.0.0/8,192.168.0.0/16,10.0.0.0/8
    volumes:
      - repository:/usr/share/nginx/html/git
      - auth:/etc/nginx/auth
    depends_on:
      - "rest"
  rest:
    build:
      context: ./rest
      dockerfile: Dockerfile
    container_name:
      cometar_rest
    volumes:
      - repository:/update-hook-repository:ro
    depends_on:
      - "fuseki"
  fuseki:
    build:
      context: ./fuseki
      dockerfile: Dockerfile
    container_name:
      cometar_fuseki
    volumes:
      - fuseki-default:/fuseki
