version: 1
disable_existing_loggers: false

formatters:
    standard:
        format: "[%(asctime)s] {%(name)s:%(lineno)d (%(funcName)s)} %(levelname)s - %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
    error:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: /var/log/cometar/cometar_DEBUG.log
        maxBytes: 10485760 # 10MB
        backupCount: 5
        encoding: utf8

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: /var/log/cometar/cometar.log
        maxBytes: 10485760 # 10MB
        backupCount: 5
        encoding: utf8

    critical_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: CRITICAL
        formatter: standard
        filename: /var/log/cometar/cometar_CRITICAL.log
        maxBytes: 10485760 # 10MB
        backupCount: 5
        encoding: utf8

# root:
#     # level: DEBUG
#     handlers: [console, debug_file_handler, info_file_handler, critical_file_handler]
#     propogate: yes

loggers:
    <module>:
        level: INFO
        handlers: []
        propogate: yes

    requests.packages.urllib3:
        level: WARNING
        handlers: [console, critical_file_handler]
        propogate: yes

    git:
        level: WARNING
        handlers: [console, debug_file_handler, info_file_handler, critical_file_handler]
        propogate: yes

    main:
        level: DEBUG
        handlers: [console, debug_file_handler, info_file_handler, critical_file_handler]
        propogate: yes

    cometar:
        level: DEBUG
        handlers: [console, debug_file_handler, info_file_handler, critical_file_handler]
        propogate: yes
