#!/bin/sh
## Description: Tell fuseki server to reload data from git

## Call the rest api to load newly committed data
curl -s -H "Accept: application/json" "${REST_SERVER}/fuseki_load_live" >&2
sleep 1 ## Give the api a little time to write files to disk and ensure its ready for the next request
## Call the rest api to update provenance data
curl -s -H "Accept: application/json" "${REST_SERVER}/update_provenance" >&2
