#!/bin/bash

echo "UPDATE HOOK called for ref $3"

upload_verification=$(curl -s -H "Accept: application/json" "$COMETAR_FLASK_SERVER/rdf_verification/$3")

echo $upload_verification | jq -r '.response'

exitcode=$(echo $upload_verification | jq -r '.exitcode')
if [ "$exitcode" == "0" ]; then
    echo "VERIFICATION SUCCESS"
    echo "$3" > "$COMETAR_PIPES_DIR/git_update_hook"
    exit 1
else
    echo "VERIFICATION FAILED"
    exit 1
fi
