name: Auto-tag PR with next SemVer
## Update only the git commit tag (other actions can be triggered by this)
## See: https://github.com/anothrNick/github-tag-action
## Add change type (#major, #minor, #patch) to the PR commit message

on:
  pull_request:
    branches:
      - master

env:
  REGISTRY: ghcr.io

jobs:
  tag_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: none
