name: Tag accepted CoMetaR Docker Images with version (from PR)
## Update the docker image/package tags by finding the commit sha which was built in the branch
## Adapted from: https://github.com/marketplace/actions/docker-registry-tag
## Manually tag the PR which you've accepted - we find the commit id which was last included in that merge and assume its what was built and accepted (it should be!)

on:
  push:
    tags:
      - v[0-9]+.[0-9]+**

env:
  REGISTRY: ghcr.io

jobs:
  proxy:
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/master' &&
      startsWith(github.event.head_commit.message, 'Merge pull request')
    steps:
      - name: Prepare Version
        id: prep
        run: |
          echo ::set-output name=commit_sha::$(git show --format="%P" "${{ github.sha }}" | cut -d" " -f2)
          echo ::set-output name=repository::$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      - name: Add git Version tag to Docker Image
        uses: shrink/actions-docker-registry-tag@v1
        with:
          registry: '${{ REGISTRY }}'
          repository: '${{ env.OWNER_APPLICATION_NAME }}/${{ github.repository }}-${{ github.job }}'
          target: 'sha-${{ steps.prep.outputs.commit_sha }}'
          tags: |
            'v${{ steps.prep.outputs.version }}'
            '${{ latest }}'
  web:
    runs-on: ubuntu-latest
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/master' &&
      startsWith(github.event.head_commit.message, 'Merge pull request')
    steps:
      - name: Prepare Version
        id: prep
        run: |
          echo ::set-output name=commit_sha::$(git show --format="%P" "${{ github.sha }}" | cut -d" " -f2)
          echo ::set-output name=repository::$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      - name: Add git Version tag to Docker Image
        uses: shrink/actions-docker-registry-tag@v1
        with:
          registry: '${{ REGISTRY }}'
          repository: '${{ env.OWNER_APPLICATION_NAME }}/${{ github.repository }}-${{ github.job }}'
          target: 'sha-${{ steps.prep.outputs.commit_sha }}'
          tags: |
            'v${{ steps.prep.outputs.version }}'
            '${{ latest }}'
  git:
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/master' &&
      startsWith(github.event.head_commit.message, 'Merge pull request')
    steps:
      - name: Prepare Version
        id: prep
        run: |
          echo ::set-output name=commit_sha::$(git show --format="%P" "${{ github.sha }}" | cut -d" " -f2)
          echo ::set-output name=repository::$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      - name: Add git Version tag to Docker Image
        uses: shrink/actions-docker-registry-tag@v1
        with:
          registry: '${{ REGISTRY }}'
          repository: '${{ env.OWNER_APPLICATION_NAME }}/${{ github.repository }}-${{ github.job }}'
          target: 'sha-${{ steps.prep.outputs.commit_sha }}'
          tags: |
            'v${{ steps.prep.outputs.version }}'
            '${{ latest }}'
  fuseki:
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/master' &&
      startsWith(github.event.head_commit.message, 'Merge pull request')
    steps:
      - name: Prepare Version
        id: prep
        run: |
          echo ::set-output name=commit_sha::$(git show --format="%P" "${{ github.sha }}" | cut -d" " -f2)
          echo ::set-output name=repository::$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      - name: Add git Version tag to Docker Image
        uses: shrink/actions-docker-registry-tag@v1
        with:
          registry: '${{ REGISTRY }}'
          repository: '${{ env.OWNER_APPLICATION_NAME }}/${{ github.repository }}-${{ github.job }}'
          target: 'sha-${{ steps.prep.outputs.commit_sha }}'
          tags: |
            'v${{ steps.prep.outputs.version }}'
            '${{ latest }}'
  rest:
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/master' &&
      startsWith(github.event.head_commit.message, 'Merge pull request')
    steps:
      - name: Prepare Version
        id: prep
        run: |
          echo ::set-output name=commit_sha::$(git show --format="%P" "${{ github.sha }}" | cut -d" " -f2)
          echo ::set-output name=repository::$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      - name: Add git Version tag to Docker Image
        uses: shrink/actions-docker-registry-tag@v1
        with:
          registry: '${{ REGISTRY }}'
          repository: '${{ env.OWNER_APPLICATION_NAME }}/${{ github.repository }}-${{ github.job }}'
          target: 'sha-${{ steps.prep.outputs.commit_sha }}'
          tags: |
            'v${{ steps.prep.outputs.version }}'
            '${{ latest }}'
