name: Build CoMetaR Docker Image

on:
  push:
    branches-ignore:
      - "master"

env:
  REGISTRY: ghcr.io
  OWNER_APPLICATION_NAME: ${{ github.repository }}

jobs:
  proxy:
    runs-on: ubuntu-latest
    ## Only run job if commit message doesn't contain "WIP:" or "ci skip"
    if: |
      !startsWith(github.event.head_commit.message, 'WIP:') ||
      !contains(github.event.head_commit.message, 'ci skip')
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Version
        id: prep
        run: |
          echo ::set-output name=repository::$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
      - name: Build and push docker image for ${{ github.job }}
        uses: docker/build-push-action@v2
        with:
          context: ./${{ github.job }}
          file: ./${{ github.job }}/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER_APPLICATION_NAME }}/${{ github.event.repository.name }}-${{ github.job }}:build-latest
            ${{ env.REGISTRY }}/${{ env.OWNER_APPLICATION_NAME }}/${{ github.event.repository.name }}-${{ github.job }}:build-${{ github.run_number }}
            ${{ env.REGISTRY }}/${{ env.OWNER_APPLICATION_NAME }}/${{ github.event.repository.name }}-${{ github.job }}:sha-${{ github.sha }}
          push: true
  web:
    runs-on: ubuntu-latest
    ## Only run job if commit message doesn't contain "WIP:" or "ci skip"
    if: |
      !startsWith(github.event.head_commit.message, 'WIP:') ||
      !contains(github.event.head_commit.message, 'ci skip')
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Version
        id: prep
        run: |
          echo ::set-output name=repository::$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
      - name: Build and push docker image for ${{ github.job }}
        uses: docker/build-push-action@v2
        with:
          context: ./${{ github.job }}
          file: ./${{ github.job }}/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER_APPLICATION_NAME }}/${{ github.event.repository.name }}-${{ github.job }}:build-latest
            ${{ env.REGISTRY }}/${{ env.OWNER_APPLICATION_NAME }}/${{ github.event.repository.name }}-${{ github.job }}:build-${{ github.run_number }}
            ${{ env.REGISTRY }}/${{ env.OWNER_APPLICATION_NAME }}/${{ github.event.repository.name }}-${{ github.job }}:sha-${{ github.sha }}
          push: true
  git:
    runs-on: ubuntu-latest
    ## Only run job if commit message doesn't contain "WIP:" or "ci skip"
    if: |
      !startsWith(github.event.head_commit.message, 'WIP:') ||
      !contains(github.event.head_commit.message, 'ci skip')
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Version
        id: prep
        run: |
          echo ::set-output name=repository::$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
      - name: Build and push docker image for ${{ github.job }}
        uses: docker/build-push-action@v2
        with:
          context: ./${{ github.job }}
          file: ./${{ github.job }}/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER_APPLICATION_NAME }}/${{ github.event.repository.name }}-${{ github.job }}:build-latest
            ${{ env.REGISTRY }}/${{ env.OWNER_APPLICATION_NAME }}/${{ github.event.repository.name }}-${{ github.job }}:build-${{ github.run_number }}
            ${{ env.REGISTRY }}/${{ env.OWNER_APPLICATION_NAME }}/${{ github.event.repository.name }}-${{ github.job }}:sha-${{ github.sha }}
          push: true
  fuseki:
    runs-on: ubuntu-latest
    ## Only run job if commit message doesn't contain "WIP:" or "ci skip"
    if: |
      !startsWith(github.event.head_commit.message, 'WIP:') ||
      !contains(github.event.head_commit.message, 'ci skip')
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Version
        id: prep
        run: |
          echo ::set-output name=repository::$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
      - name: Build and push docker image for ${{ github.job }}
        uses: docker/build-push-action@v2
        with:
          context: ./${{ github.job }}
          file: ./${{ github.job }}/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER_APPLICATION_NAME }}/${{ github.event.repository.name }}-${{ github.job }}:build-latest
            ${{ env.REGISTRY }}/${{ env.OWNER_APPLICATION_NAME }}/${{ github.event.repository.name }}-${{ github.job }}:build-${{ github.run_number }}
            ${{ env.REGISTRY }}/${{ env.OWNER_APPLICATION_NAME }}/${{ github.event.repository.name }}-${{ github.job }}:sha-${{ github.sha }}
          push: true
  rest:
    runs-on: ubuntu-latest
    ## Only run job if commit message doesn't contain "WIP:" or "ci skip"
    if: |
      !startsWith(github.event.head_commit.message, 'WIP:') ||
      !contains(github.event.head_commit.message, 'ci skip')
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Version
        id: prep
        run: |
          echo ::set-output name=repository::$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
      - name: Build and push docker image for ${{ github.job }}
        uses: docker/build-push-action@v2
        with:
          context: ./${{ github.job }}
          file: ./${{ github.job }}/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER_APPLICATION_NAME }}/${{ github.event.repository.name }}-${{ github.job }}:build-latest
            ${{ env.REGISTRY }}/${{ env.OWNER_APPLICATION_NAME }}/${{ github.event.repository.name }}-${{ github.job }}:build-${{ github.run_number }}
            ${{ env.REGISTRY }}/${{ env.OWNER_APPLICATION_NAME }}/${{ github.event.repository.name }}-${{ github.job }}:sha-${{ github.sha }}
          push: true
